import React from 'react'

export default function AboutUs() {
  return (
    <div>
        AboutUs
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo incidunt dolores explicabo labore libero obcaecati harum nesciunt eos magni et dignissimos, placeat officia officiis atque unde inventore voluptas! Excepturi ipsum ab nihil. Recusandae veritatis suscipit sapiente natus maiores vitae ratione eos! Cumque illo quam tempora nam libero itaque molestias ipsam qui impedit omnis. Minima suscipit debitis corporis qui quisquam quod dolorum consequatur dignissimos consectetur? Obcaecati quia, earum enim ad, praesentium rerum deserunt iusto est aspernatur voluptatibus fugiat possimus perferendis. Aperiam, sit beatae omnis laudantium sequi minima et similique ut autem praesentium consequatur, eaque ipsum. Quis, autem? Accusamus possimus laborum alias.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo incidunt dolores explicabo labore libero obcaecati harum nesciunt eos magni et dignissimos, placeat officia officiis atque unde inventore voluptas! Excepturi ipsum ab nihil. Recusandae veritatis suscipit sapiente natus maiores vitae ratione eos! Cumque illo quam tempora nam libero itaque molestias ipsam qui impedit omnis. Minima suscipit debitis corporis qui quisquam quod dolorum consequatur dignissimos consectetur? Obcaecati quia, earum enim ad, praesentium rerum deserunt iusto est aspernatur voluptatibus fugiat possimus perferendis. Aperiam, sit beatae omnis laudantium sequi minima et similique ut autem praesentium consequatur, eaque ipsum. Quis, autem? Accusamus possimus laborum alias.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo incidunt dolores explicabo labore libero obcaecati harum nesciunt eos magni et dignissimos, placeat officia officiis atque unde inventore voluptas! Excepturi ipsum ab nihil. Recusandae veritatis suscipit sapiente natus maiores vitae ratione eos! Cumque illo quam tempora nam libero itaque molestias ipsam qui impedit omnis. Minima suscipit debitis corporis qui quisquam quod dolorum consequatur dignissimos consectetur? Obcaecati quia, earum enim ad, praesentium rerum deserunt iusto est aspernatur voluptatibus fugiat possimus perferendis. Aperiam, sit beatae omnis laudantium sequi minima et similique ut autem praesentium consequatur, eaque ipsum. Quis, autem? Accusamus possimus laborum alias.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo incidunt dolores explicabo labore libero obcaecati harum nesciunt eos magni et dignissimos, placeat officia officiis atque unde inventore voluptas! Excepturi ipsum ab nihil. Recusandae veritatis suscipit sapiente natus maiores vitae ratione eos! Cumque illo quam tempora nam libero itaque molestias ipsam qui impedit omnis. Minima suscipit debitis corporis qui quisquam quod dolorum consequatur dignissimos consectetur? Obcaecati quia, earum enim ad, praesentium rerum deserunt iusto est aspernatur voluptatibus fugiat possimus perferendis. Aperiam, sit beatae omnis laudantium sequi minima et similique ut autem praesentium consequatur, eaque ipsum. Quis, autem? Accusamus possimus laborum alias.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo incidunt dolores explicabo labore libero obcaecati harum nesciunt eos magni et dignissimos, placeat officia officiis atque unde inventore voluptas! Excepturi ipsum ab nihil. Recusandae veritatis suscipit sapiente natus maiores vitae ratione eos! Cumque illo quam tempora nam libero itaque molestias ipsam qui impedit omnis. Minima suscipit debitis corporis qui quisquam quod dolorum consequatur dignissimos consectetur? Obcaecati quia, earum enim ad, praesentium rerum deserunt iusto est aspernatur voluptatibus fugiat possimus perferendis. Aperiam, sit beatae omnis laudantium sequi minima et similique ut autem praesentium consequatur, eaque ipsum. Quis, autem? Accusamus possimus laborum alias.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo incidunt dolores explicabo labore libero obcaecati harum nesciunt eos magni et dignissimos, placeat officia officiis atque unde inventore voluptas! Excepturi ipsum ab nihil. Recusandae veritatis suscipit sapiente natus maiores vitae ratione eos! Cumque illo quam tempora nam libero itaque molestias ipsam qui impedit omnis. Minima suscipit debitis corporis qui quisquam quod dolorum consequatur dignissimos consectetur? Obcaecati quia, earum enim ad, praesentium rerum deserunt iusto est aspernatur voluptatibus fugiat possimus perferendis. Aperiam, sit beatae omnis laudantium sequi minima et similique ut autem praesentium consequatur, eaque ipsum. Quis, autem? Accusamus possimus laborum alias.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo incidunt dolores explicabo labore libero obcaecati harum nesciunt eos magni et dignissimos, placeat officia officiis atque unde inventore voluptas! Excepturi ipsum ab nihil. Recusandae veritatis suscipit sapiente natus maiores vitae ratione eos! Cumque illo quam tempora nam libero itaque molestias ipsam qui impedit omnis. Minima suscipit debitis corporis qui quisquam quod dolorum consequatur dignissimos consectetur? Obcaecati quia, earum enim ad, praesentium rerum deserunt iusto est aspernatur voluptatibus fugiat possimus perferendis. Aperiam, sit beatae omnis laudantium sequi minima et similique ut autem praesentium consequatur, eaque ipsum. Quis, autem? Accusamus possimus laborum alias.
        </div>
    </div>
  )
}
